### ISSUE TITLE
invoices/list does not contain status

### ISSUE THREAD

**Issue by ligi** [liquidity-network/liquidity-sdk#6]
might be caused by this hotfix: https://github.com/liquidity-network/liquidity-sdk/commit/f693a032bd280434b15d1ee045e92b25b59b3acc

**Comment by thibmeu** [comment]
Fixed in 1ae89105de0d35abc3e3aede884332470475500f

**Comment by ligi** [comment]
Thanks!

**Comment by ligi** [comment]
confirmed to work now - closing
